import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { minify } from "./css-utils.mjs";
import { generateGrid } from "./generate-grid.mjs";
import { generateLegacy } from "./generate-legacy.mjs";
import { generateResponsive } from "./generate-responsive.mjs";
import { generateUtilities } from "./generate-utilities.mjs";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const scssDir = path.join(rootDir, "src", "scss");
const generatedDir = path.join(scssDir, "generated");
const distDir = path.join(rootDir, "dist");
const banner = "/* clasecitas-vlv v0.1.0 | MIT License */";
const generatedBanner = "/* This file is generated by scripts/build.mjs. Do not edit directly. */";

async function readSourceScss(fileName) {
  return readFile(path.join(scssDir, fileName), "utf8");
}

async function writeGenerated(fileName, css) {
  await writeFile(path.join(generatedDir, fileName), `${generatedBanner}\n\n${css}\n`);
}

await mkdir(generatedDir, { recursive: true });
await mkdir(distDir, { recursive: true });

const tokens = await readSourceScss("_tokens.scss");
const base = await readSourceScss("_base.scss");
const utilities = generateUtilities();
const grid = generateGrid();
const responsive = generateResponsive();
const legacy = generateLegacy();

await writeGenerated("_utilities.scss", utilities);
await writeGenerated("_grid.scss", grid);
await writeGenerated("_responsive.scss", responsive);
await writeGenerated("_legacy.scss", legacy);

const css = [banner, tokens, base, utilities, grid, responsive].join("\n\n");
const legacyCss = [banner, legacy].join("\n\n");

await writeFile(path.join(distDir, "clasecitas.css"), `${css}\n`);
await writeFile(path.join(distDir, "clasecitas.min.css"), `${minify(css)}\n`);
await writeFile(path.join(distDir, "legacy.css"), `${legacyCss}\n`);
await writeFile(path.join(distDir, "legacy.min.css"), `${minify(legacyCss)}\n`);

